### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'Dimension' and 'int', please use // instead

### ISSUE THREAD

**Issue by AIGirl10** [ciber-lab/pictor-ppe#17]
Write running inference program [Detection-Example.ipynb](https://github.com/ciber-lab/pictor-ppe/blob/master/Detection-Example.ipynb) -> inference.py

```sh
python3 inference.py
```

- Error 
```sh
022-04-22 10:00:44.397870: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
  File "inference.py", line 125, in <module>
    img = get_detection(img)
  File "inference.py", line 100, in get_detection
    classes_can_overlap=False)
  File "/home/user/Videos/newpro/ppe/pictor-ppe/src/yolo3/detect.py", line 60, in detection
    grid_i = tf.reshape( np.arange(grid_h), [-1, 1, 1, 1] )
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 532, in __truediv__
    "please use // instead".format(type(other).__name__))
TypeError: unsupported operand type(s) for /: 'Dimension' and 'int', please use // instead
```

@nipundebnath can you help me ?

**Comment by AIGirl10** [comment]
Error solved, it was because I was using wrong version on tensorflow, installed tensorflow 2.0 and now its working
